### ISSUE TITLE
setDirection is not working

### ISSUE THREAD

**Issue by ZakariaJawas** [salehyarahmadi/DataTable#6]
**setDirection** is not working, it is always **LTR**
setting the value from **xml** is not working either

Android 9
Minimum SDK 19
Target SDK 29

**Comment by salehyarahmadi** [comment]
> **setDirection** is not working, it is always **LTR**
> setting the value from **xml** is not working either
> 
> Android 9
> Minimum SDK 19
> Target SDK 29

I tested and it worked. Can you send your code?

**Comment by meysam2594** [comment]
سلام خسته نباشی 
خیلی خیلی عالیه ولی راست میگه توی کد نویسی وقتی میخوای چپ چینش کنی کار نمیکنه .
البته یه غلط املاییم داره که توی فایل Direction 
بجای LTR نوشتی LRT
ولی واقعا خیلی عالیه دستت درد نکنه

**Comment by ZakariaJawas** [comment]
> > **setDirection** is not working, it is always **LTR**
> > setting the value from **xml** is not working either
> > Android 9
> > Minimum SDK 19
> > Target SDK 29
> 
> I tested and it worked. Can you send your code?

I tried it in a different project and it works just fine, so i guess there was something wrong with my old project.
Thanks for your effort.
